=== firespeed/CNAM2012/XML/TP/agents.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="nom" type="xsd:string"/>
	<xsd:element name="service" type="xsd:string"/>
	<xsd:element name="personne">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nom"/>
				<xsd:element ref="service"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="personnes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="personne" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== firespeed/CNAM2012/XML/TP/agents.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="agents.xsd">
	<personne>
		<nom>Dupond</nom>
		<service>Achats</service>
	</personne>
	<personne>
		<nom>Durand</nom>
		<service>Achats</service>
	</personne>
	<personne>
		<nom>Dupuis</nom>
		<service>Courrier</service>
	</personne>
</personnes>
