=== firespeed/CNAM2012/XML/TP/annuaire.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="type_page">
		<xsd:sequence>
			<xsd:element name="titre" type="xsd:string"/>
			<xsd:element name="lien" type="xsd:string"/>
			<xsd:element name="cle_site" type="xsd:positiveInteger"/>
		</xsd:sequence>
		<xsd:attribute name="numero" type="xsd:positiveInteger" use="required"/>
		<xsd:attribute name="langue" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="type_site">
		<xsd:sequence>
			<xsd:element name="nom" type="xsd:string"/>
			<xsd:element name="url" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="numero" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="type_annuaire">
		<xsd:sequence>
			<xsd:element name="page" type="type_page" maxOccurs="unbounded">
				<xsd:unique name="cle_page">
					<xsd:selector xpath=".//page"/>
					<xsd:field xpath="./@numero"/>
				</xsd:unique>
			</xsd:element>
			<xsd:element name="site" type="type_site" maxOccurs="unbounded">
				<xsd:key name="num_site">
					<xsd:selector xpath=".//site"/>
					<xsd:field xpath="./@numero"/>
				</xsd:key>
				<xsd:keyref name="cle_site" refer="num_site">
					<xsd:selector xpath=".//page"/>
					<xsd:field xpath="./cle_site"/>
				</xsd:keyref>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="annuaire" type="type_annuaire"/>
</xsd:schema>

=== firespeed/CNAM2012/XML/TP/annuaire.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<annuaire xsi:noNamespaceSchemaLocation="annuaire.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	  <page numero="1" langue="US">
		  <titre>XML Schema</titre>
		  <lien>http://www.w3.org/XML/Schema/</lien>
		  <cle_site>1</cle_site>
	  </page>
	  
	  <page numero="2" langue="FR">
		  <titre>XML Schema tome 0 : Introduction</titre>
		  <lien>http://xmlfr.org/w3c/TR/xmlschema-0/</lien>
		  <cle_site>1</cle_site>
	  </page>
  
	  <page numero="3" langue="FR">
		  <titre>XML Schema tome 1 : Structures</titre>
		  <lien>http://xmlfr.org/w3c/TR/xmlschema-1/</lien>
		  <cle_site>2</cle_site>
	  </page>

	  <site numero="1"> 
		  <nom>W3C</nom>
		  <url>http://www.w3.org/</url>
	  </site>
  
	  <site numero="2">
		  <nom>XMLfr</nom>
		  <url>http://www.xmlfr.org/</url>
	  </site>
</annuaire>
