=== firespeed/CNAM2012/XML/TP/bibliographie.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Déclarations des imbrications -->
	<!ELEMENT bibliographie (livre|article)*>
	<!ELEMENT livre (titre, auteur+, edition, avis?)>
	<!ELEMENT edition (editeur, lieu_edition, lieu_impression, isbn)>
	<!ELEMENT article (titre, auteur+, journal)>
	<!ELEMENT journal (page, num_journal)>

<!-- Déclarations des structures des balises en fin d'arborecence -->
	<!ELEMENT titre (#PCDATA)>
	<!ELEMENT auteur (#PCDATA)>
	<!ELEMENT editeur (#PCDATA)>
	<!ELEMENT lieu_edition (#PCDATA)>
	<!ELEMENT lieu_impression (#PCDATA)>
	<!ELEMENT isbn (#PCDATA)>
	<!ELEMENT avis (#PCDATA)>
	<!ELEMENT page (#PCDATA)>
	<!ELEMENT num_journal (#PCDATA)>
	<!ELEMENT annee (#PCDATA)>


<!-- Déclarations des attributs -->

<!-- Avec un attribut facultatif -->
	<!ATTLIST titre soustitre CDATA #IMPLIED>
	<!ATTLIST tome nb_pages CDATA #REQUIRED soustitre CDATA #IMPLIED>

<!-- Avec une valeur par défaut -->
	<!ATTLIST journal nom_journal CDATA "Feuille de Chou" >

<!-- Avec une énumération -->
	<!ATTLIST journal annee (2000 | 2001 | 2002 | Avant2000 | inconnue ) #REQUIRED >

=== firespeed/CNAM2012/XML/TP/bibliographie.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE bibliographie SYSTEM "bibliographie.dtd">
<bibliographie>
	<livre>
		<titre soustitre="Ma vie">Live</titre>
		<auteur>Georges Dupond</auteur>
		<edition>
			<editeur>Folio</editeur>
			<lieu_edition>Montbeliard</lieu_edition>
			<lieu_impression>Belfort</lieu_impression>
			<isbn>2-033-444-025</isbn>
		</edition>
		<avis>BOF!</avis>
	</livre>
	<article>
		<titre>DOM SAX XML</titre>
		<auteur>G.Delrhue</auteur>
		<auteur>P.Anderson</auteur>
		<journal nom_journal="01 Informatique" annee="2002">
			<page>4	</page>
			<num_journal>1</num_journal>
		</journal>
	</article>
	<article>
		<titre>Java</titre>
		<auteur>Sun Microsystem</auteur>
		<journal annee="2002">
			<page>4</page>
			<num_journal>2</num_journal>
		</journal>
	</article>
</bibliographie>
