=== firespeed/CNAM2012/XML/TP/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="typeNomComplet">
		<xsd:sequence>
			<xsd:element name="nom" type="xsd:string"/>
			<xsd:element name="prenom" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="typeAdresse">
		<xsd:sequence>
			<xsd:element name="num_rue" type="xsd:int"/>
			<xsd:element name="rue" type="xsd:string"/>
			<xsd:element name="ville" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="typeContact">
		<xsd:sequence>
			<xsd:element name="telephone" type="xsd:string"/>
			<xsd:element name="fax" type="xsd:string"/>
			<xsd:element name="email" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="typeClient">
		<xsd:sequence>
			<xsd:element name="nom_complet" type="typeNomComplet"/>
			<xsd:element name="adresse" type="typeAdresse"/>
			<xsd:element name="contact" type="typeContact"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="client" type="typeClient"/>
</xsd:schema>

=== firespeed/CNAM2012/XML/TP/client_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="client.xsd">
	<nom_complet>
		<nom>Fino</nom>
		<prenom>Jean-Marie</prenom>
	</nom_complet>
	<adresse>
		<num_rue>24</num_rue>
		<rue>Grand chemin</rue>
		<ville>Montb√©liard</ville>
	</adresse>
	<contact>
		<telephone>03-81-90-99-00</telephone>
		<fax>03-81-90-99-01</fax>
		<email>jmfino@divae.fr</email>
	</contact>
</client>
