=== firespeed/CNAM2012/XML/TP/employes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:complexType name="personneinfo">
	  <xsd:sequence>
		<xsd:element name="prenom" type="xsd:string"/>
		<xsd:element name="nom" type="xsd:string"/>
	  </xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="fullpersonneinfo">
	  <xsd:complexContent>
		<xsd:extension base="personneinfo">
		  <xsd:sequence>
			<xsd:element name="addresse" type="xsd:string"/>
			<xsd:element name="ville" type="xsd:string"/>
			<xsd:element name="pays" type="xsd:string"/>
		  </xsd:sequence>
		</xsd:extension>
	  </xsd:complexContent>
	</xsd:complexType> 

	<xsd:complexType name="type_employe">
	  <xsd:sequence>
		<xsd:element name="employe" type="personneinfo" 
			minOccurs="0" maxOccurs="unbounded" />
		<xsd:element name="employe_full" type="fullpersonneinfo" 
		minOccurs="0" maxOccurs="unbounded" />
	  </xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="employes" type="type_employe" />

</xsd:schema>

=== firespeed/CNAM2012/XML/TP/employe.xml
<?xml version="1.0" encoding="UTF-8"?>
<employes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="employes.xsd">
	<employe>	
		<prenom>Georges</prenom>
		<nom>Durand</nom>
		<addresse>37 grande rue</addresse>
		<ville>Montb√©liard</ville>
		<pays>France</pays>
	</employe>
	<employe>	
		<prenom>Albert</prenom>
		<nom>Dupont</nom>
	</employe>

</employes>

=== firespeed/CNAM2012/XML/TP/employes.xml
<?xml version="1.0" encoding="UTF-8"?>
<employes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="employes.xsd">

	<employe>	
		<prenom>Albert</prenom>
		<nom>Dupont</nom>
	</employe>	
	
	<employe_full>	
		<prenom>Georges</prenom>
		<nom>Durand</nom>
		<addresse>37 grande rue</addresse>
		<ville>Montb√©liard</ville>
		<pays>France</pays>
	</employe_full>

</employes>
