=== firespeed/CNAM2012/XML/TP/lesProjets.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lesProjets (projet+, employé+)>
<!ELEMENT projet (but, membre_équipe+)>
<!ELEMENT employé (nom, tâches+)>

<!ELEMENT but (#PCDATA)>
<!ELEMENT membre_équipe EMPTY>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT tâches EMPTY>

<!ATTLIST tâches projet_id IDREF #REQUIRED>
<!ATTLIST projet projet_id ID #REQUIRED>
<!ATTLIST membre_équipe employé IDREF #REQUIRED>
<!ATTLIST employé numéro_sécu ID #REQUIRED>

=== firespeed/CNAM2012/XML/TP/lesProjets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lesProjets SYSTEM "lesProjets.dtd">
<lesProjets>
	<projet projet_id="p1">
		<but>Plan de développement stratégique</but>
		<membre_équipe employé="ss123-45-6789"/>
		<membre_équipe employé="ss876-54-3210"/>
	</projet>
	<projet projet_id="p2">
		<but>Déployez Linux</but>
		<membre_équipe employé="ss123-45-6789"/>
		<membre_équipe employé="ss876-12-3456"/>
	</projet>
	<employé numéro_sécu="ss123-45-6789">
		<nom>Fred Smith</nom>
		<tâches projet_id="p1"/>
		<tâches projet_id="p2"/>
	</employé>
	<employé numéro_sécu="ss876-54-3210">
		<nom>Jill Jones</nom>
		<tâches projet_id="p1"/>
	</employé>
	<employé numéro_sécu="ss876-12-3456">
		<nom>Sydney Lee</nom> 
		<tâches projet_id="p2"/>
	</employé>
</lesProjets>
