=== firespeed/CNAM2012/XML/TP/librairie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xsd:attributeGroup name="groupe_attributs_livre">
	<xsd:attribute name="isbn" type="xsd:string" use="required"/>
	<xsd:attribute name="categorie" type="xsd:string"/>
</xsd:attributeGroup>

<xsd:group name="groupe_elements_livre" >
	<xsd:sequence>
		<xsd:element name="titre" type="xsd:string" />
		<xsd:element name="auteur" type="xsd:string" 
			minOccurs="1" maxOccurs="unbounded" />
		<xsd:element name="editeur" type="xsd:string" />
	</xsd:sequence>
</xsd:group>

<xsd:complexType name="type_livre">
	<xsd:sequence>
		<xsd:group ref="groupe_elements_livre" />
	</xsd:sequence>
	<xsd:attributeGroup ref="groupe_attributs_livre" />
</xsd:complexType>

<xsd:complexType name="type_librairie" >
	<xsd:sequence>
		<xsd:element name ="livre" type="type_livre" 
		maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>	

<xsd:element name="librairie" type="type_librairie"/>

</xsd:schema>

=== firespeed/CNAM2012/XML/TP/librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<librairie 	xsi:noNamespaceSchemaLocation="librairie.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<livre isbn="2212110472" categorie="XML">
		<titre>
			Services Web avec XML, SOAP, WSDL, UDDI, ebXML ...
		</titre>
		<auteur>Jean-Marie Chauvet</auteur>
		<editeur>Eyrolles</editeur>
	</livre>

	<livre isbn="2100065203" categorie="XML">
		<titre>XML Manuel de référence</titre>
		<auteur>R. Wyke</auteur>
		<auteur>S. Rehman</auteur>
		<auteur>B. Leupen</auteur>
		<editeur>Microsoft Press</editeur>
	</livre>

	<livre isbn="1928994474" categorie="XML">
		<titre>XML.NET Developer's Guide</titre>
		<auteur>Collectif</auteur>
		<editeur>Syngress</editeur>
	</livre>

</librairie>
